name: Build and Publish OpenFGA Docker Image

on:
  workflow_dispatch:
    inputs:
      openfga_version:
        description: 'OpenFGA version to build (e.g., v1.10.3)'
        required: true
        type: string

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/openfga_run

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version number
        id: version
        run: |
          VERSION="${{ github.event.inputs.openfga_version }}"
          # Remove 'v' prefix if present
          VERSION_NUMBER="${VERSION#v}"
          echo "version=${VERSION_NUMBER}" >> $GITHUB_OUTPUT
          echo "version_with_v=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            OPENFGA_VERSION=${{ steps.version.outputs.version_with_v }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version_with_v }}
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version_number }}
            ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: ./README.md
        continue-on-error: true
